build: false

platform:
  - x64

clone_folder: c:\projects\project-code

cache:
  - c:\ProgramData\chocolatey\bin -> .appveyor.yml
  - c:\ProgramData\chocolatey\lib -> .appveyor.yml
  - c:\ProgramData\ComposerSetup -> .appveyor.yml
  - c:\tools\php -> .appveyor.yml

environment:
  global:
    COMPOSER_NO_INTERACTION: 1
    ANSICON: 121x90 (121x90) # Console colors

  ffmpeg_download: https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-20190225-f948082-win64-static.zip

  matrix:
    - PYTHON: "C:\\Python37"
      PYTHON_VERSION: 3.7
      PYTHON_ARCH: 32

    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: 3.6
      PYTHON_ARCH: 32

init:
  - ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%

install:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - python --version
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - python -m pip install -U pip
  - python -m easy_install -U setuptools
  - pip install -e .[test]
  - ps: Start-FileDownload $env:ffmpeg_download

  - 7z x ffmpeg-20190225-f948082-win64-static.zip
  - PATH=%PATH%;%cd%\ffmpeg-20190225-f948082-win64-static\bin

test_script:
  - cd c:\projects\project-code
  - python -m unittest