language: python

before_install:
  - sudo apt-get update
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;

matrix:
  include:
    - python: 3.7
    - python: 3.6

install:
  - sudo apt-get install ffmpeg

script:
  - ffmpeg -y -i /home/travis/build/aminyazdanpanah/python-ffmpeg-video-streaming/ffmpeg_streaming/tests/files/test.mp4 -c:v libx265 -bf 1 -keyint_min 120 -g 120 -sc_threshold 0 -b_strategy 0 -use_timeline 1 -use_template 1 -f dash -map 0 -b:v:0 88k -s:v:0 256x144 -map 0 -b:v:1 117k -s:v:1 426x240 -map 0 -b:v:2 176k -s:v:2 480x270 -strict -2 "/home/travis/build/aminyazdanpanah/python-ffmpeg-video-streaming/ffmpeg_streaming/tests/files/dash/test.mpd"
  - python -m unittest