language: python

before_install:
  - python -m pip install --upgrade pip
  - pip install requests
  - pip install boto3
  - pip install google-cloud-storage
  - pip install azure-storage-blob
  - >
    [ -f ffmpeg-release/ffmpeg ] || (
        curl -O https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz &&
        mkdir -p ffmpeg-release &&
        tar Jxf ffmpeg-release-amd64-static.tar.xz --strip-components=1 -C ffmpeg-release
    )

matrix:
  include:
    - python: 3.7
    - python: 3.6

script:
  - export PATH=$(readlink -f ffmpeg-release):$PATH
  - python -m unittest

cache:
  directories:
    - ffmpeg-release