language: python

before_install:
  - >
    [ -f ffmpeg-release/ffmpeg ] || (
        curl -O https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz &&
        mkdir -p ffmpeg-release &&
        tar Jxf ffmpeg-release-amd64-static.tar.xz --strip-components=1 -C ffmpeg-release
    )
matrix:
  include:
    - python: 3.7
    - python: 3.6

script:
  - export PATH=$(readlink -f ffmpeg-release):$PATH
  - ffmpeg -y -i /home/travis/build/aminyazdanpanah/python-ffmpeg-video-streaming/ffmpeg_streaming/tests/files/test.mp4 -c:v libx265 -bf 1 -keyint_min 120 -g 120 -sc_threshold 0 -b_strategy 0 -use_timeline 1 -use_template 1 -f dash -map 0 -b:v:0 88k -s:v:0 256x144 -map 0 -b:v:1 117k -s:v:1 426x240 -map 0 -b:v:2 176k -s:v:2 480x270 -strict -2 "/home/travis/build/aminyazdanpanah/python-ffmpeg-video-streaming/ffmpeg_streaming/tests/files/dash/test.mpd"
  - python -m unittest

cache:
  directories:
    - ffmpeg-release