language: python

before_install:
  - sudo apt-get update
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;

matrix:
  include:
    - python: 3.7
    - python: 3.6

install:
  - sudo apt-get install ffmpeg

script:
  - python -m unittest