language: python
before_install:
  - sudo apt-get update
  - travis_retry composer self-update
  - >
    [ -f ffmpeg-release/ffmpeg ] || (
        curl -O https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz &&
        mkdir -p ffmpeg-release &&
        tar Jxf ffmpeg-release-amd64-static.tar.xz --strip-components=1 -C ffmpeg-release
    )
matrix:
  include:
    - python: 3.4
    - python: 3.5
    - python: 3.6

script:
  - python -m unittest